name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 5.2.0
          - 5.1.0~rc1
          - 5.0.0
          - 4.14.0

    runs-on: ${{ matrix.os }}

    env:
      OPAMCONFIRMLEVEL: unsafe-yes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: echo | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) --dev
      - run: sudo apt install bubblewrap

      - run: opam init --compiler ${{ matrix.ocaml-version }}

      - run: opam install --deps-only . --with-test --with-doc

      - run: opam exec -- dune build @install

      - run: opam exec -- dune build @runtest

      - run: opam exec -- dune build @doc

      - run: opam install .
      - run: opam reinstall -t .
      - run: opam reinstall -d .
